# Scanner gui


In [1]:
import cv2
import numpy as np

In [2]:
# we will extract the image of gerry from its context and rotate it
img = cv2.imread("gerry.png")

img_copy = np.copy(img) # we'll be drawing on these, rotating the original one


# corner coords
# t1 - 28,227
# bl - 131, 987
# br - 730 860
# tr - 572 147

# defining the starting points
src_points = []

# destination points of Image of size 600, 800
dst_points = np.array(
    [
        [0,0],
        [0, 800],
        [600, 800],
        [600, 0]
    ], np.float32
)

In [3]:
def on_click(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        if len(src_points) < 4:
            src_points.append([x, y])
            cv2.circle(img_copy, (x,y), 10, (0,0,255), -1) # last param is for thickness, if it is -1 the circle is filled
            cv2.imshow("Img", img_copy)

In [4]:
# create window and gui for src point selection
cv2.namedWindow("Img") # name of window used as hanle for callback
cv2.setMouseCallback("Img", on_click)

# show the image for the first time
cv2.imshow("Img", img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
# find the matrix which transforms the 4 starting point to the 4 dst points
src_float = np.array(src_points, dtype=np.float32)
M = cv2.getPerspectiveTransform(src_float, dst_points)
print(M)

[[ 1.18270735e+00 -1.67915241e-01 -3.04948680e+01]
 [ 4.40885008e-01  2.67155320e+00 -1.11322940e+03]
 [-3.78356253e-05  1.54347634e-04  1.00000000e+00]]


In [6]:
# applying the trasformation to the image
out_img = cv2.warpPerspective(img, M, (600, 800))

In [7]:
cv2.imshow("result", out_img)
cv2.waitKey(0)
cv2.destroyAllWindows()