In [1]:
import numpy as np

In [8]:
l = np.arange(1,10)

mat = l.reshape((3,3))
col = l.reshape((1, 9))

print(mat)
print("this shit is a cloumn!")
print(col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
this shit is a cloumn!
[[1 2 3 4 5 6 7 8 9]]


In [10]:
# Another way of adding an axis
l[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
# A way to augment the dimentions
mat[:,:, np.newaxis]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [20]:
# Concatenate
array1 = np.array([[1,2,3], [3,2,1]])
x = np.array([[7,8,9], [9,8,7]])
bnarray = np.concatenate([array1, x])

print(bnarray)


[[1 2 3]
 [3 2 1]
 [7 8 9]
 [9 8 7]]


In [82]:

bnarray = np.hstack([array1, x])
print(bnarray)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)

In [38]:
# split, specify the indeces where to split
array1 = np.arange(1,9)
x1, x2, x3 = np.split(array1, [3,5])
print("x1:", x1, "x2:", x2, "x3:", x3)

x1: [1 2 3] x2: [] x3: [1 2 3 4 5 6 7 8]


In [45]:
# height split (needs 2 dimentions)
array1 = np.arange(16).reshape((4,4))
upper, lower = np.hsplit(array1, [2])

print("upper:", upper, "\nlower:", lower)

upper: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
lower: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [46]:
# depth split (need 3 dimentsions)
array1 = np.arange(27).reshape((3,3,3))
upper, lower = np.dsplit(array1, [2])

print("upper:", upper, "\nlower:", lower)

upper: [[[ 0  1]
  [ 3  4]
  [ 6  7]]

 [[ 9 10]
  [12 13]
  [15 16]]

 [[18 19]
  [21 22]
  [24 25]]] 
lower: [[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]

 [[20]
  [23]
  [26]]]


# _______________
# Ufuncs

parallelized operations, optimized for multicore processors



In [104]:
import time
np.random.seed(0)

def compute_reciprocal(values: list):
    output= np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [111]:
array1 = np.random.randint(1,10, 10000)
stime = time.time()
out = compute_reciprocal(array1)
dur = time.time()-stime
print(f"done in {dur * 1000} ms")
stime = time.time()
out = 1.0 / array1
dur = time.time()-stime
print(f"done in {dur * 1000} ms")


done in 129.77242469787598 ms
done in 0.4856586456298828 ms


In [112]:
print(array1)
print(1+array1)
print(np.add(1,array1))

[6 1 4 ... 1 8 8]
[7 2 5 ... 2 9 9]
[7 2 5 ... 2 9 9]
