In [1]:
import numpy as np

np will always choose the strongest type: 
if a list contains a float, all elements will be cast to np floats.
If there is a string all to numpy strings
if you put an object np will use python ints and floats (slow, bad)


In [2]:
l = [3.14, 4, 5, 7]
np_l = np.array(l, dtype="int8")

datatype is important: int wh no specification will use native architecture

In [7]:
np.ones((2,3), dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
np.full((2,3), 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5)

In [ ]:
np.random.random((2,2))

In [ ]:
np.random.normal(0, 1, 5)

In [ ]:
np.random.randint(0, 10, 5)

In [ ]:
np.eye(3)

In [ ]:
np.empty((3, 2)) #will pick random points in memory

In [ ]:
my_l = np.random.randint(0,10, (3, 5, 3))

print(my_l, 
      f'''\narray dims:{my_l.ndim}
    array shape:{my_l.shape}
    array size:{my_l.size}''')